### ISSUE TITLE
Plugin broke my docuwiki

### ISSUE THREAD

**Issue by Mindpsy** [syntaxseed/dokucrypt2#14] opened 2021-08-31 08:40 UTC
Immediately after clicking the install button, a clean white sheet of the document appeared. DocuWiki is no longer working and is not responding.

**Comment by Mindpsy** [comment] 2021-08-31 09:26
> 
> 
> Immediately after clicking the install button, a clean white sheet of the document appeared. DocuWiki is no longer working and is not responding.

Решил проблему удлением папки плагина из раздела lib.

Потом снова попробовал закинув просто ваш репозиторий в папку lib в обход админ панели. В итоге появилось такое сообщение 
![изображение](https://user-images.githubusercontent.com/34247662/131478020-6a3a14ea-1e7d-4e33-9396-2aebbd7e556e.png)

**Comment by Mindpsy** [comment] 2021-08-31 09:28
> 
> 
> Immediately after clicking the install button, a clean white sheet of the document appeared. DocuWiki is no longer working and is not responding.

I solved the problem by deleting the plugin folder from the lib section.

Then I tried again by simply throwing your repository into the lib folder, bypassing the admin panel. As a result, the following message appeared
![изображение](https://user-images.githubusercontent.com/34247662/131478245-8b4bfc7c-05dd-44d8-afa0-1e083feb368b.png)

**Comment by syntaxseed** [comment] 2021-09-01 16:32
@Mindpsy looks like your DokuWiki install is missing its temp directory. Try creating one at /data/tmp and make sure it's writeable.

**Comment by Mindpsy** [comment] 2021-09-12 22:08
![изображение](https://user-images.githubusercontent.com/34247662/133004212-31a0bf91-d10b-4b65-af72-36573a79e70d.png)
![изображение](https://user-images.githubusercontent.com/34247662/133004219-01756b85-232a-4410-a32d-9afc00771b00.png)
![изображение](https://user-images.githubusercontent.com/34247662/133004234-cfd82d31-3958-4cce-8ad7-c514285b918f.png)
![изображение](https://user-images.githubusercontent.com/34247662/133004252-e624f56a-9e8b-4e7e-8c45-7236d80e8d8a.png)
![изображение](https://user-images.githubusercontent.com/34247662/133004268-5401ad1d-3ad2-4d62-97e9-3cf3f7099008.png)

Проблема ровно такая же - пустой лист, пока не удалишь папку плагина.
The problem is exactly the same - an empty sheet until you delete the plugin folder.

**Comment by syntaxseed** [comment] 2021-09-13 14:34
I'm sorry I don't really know how to debug this. I can't reproduce it. I'll keep an eye out for this happening in other contexts.

**Comment by syntaxseed** [comment] 2022-11-29 14:04
Closing due to lack of reproduceability and corroboration.

**Closed as not planned** 2022-11-29 14:07 UTC
Labels: help wanted, confirmation needed, Hacktoberfest
